language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: 1.8.7
    - rvm: ree
    - rvm: rbx-19mode

services:
  - mongodb
before_script:
  - cp config/mongoid.yml.sample config/mongoid.yml
script:
  - bundle exec rspec spec
